name: Nightly

on:
  push:
    branches:
      - nu
  pull_request_review:
    branches:
      - nu

jobs:
  windows-x64:
    name: Windows x64
    runs-on: windows-2019
    defaults:
      run:
        shell: cmd
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.8

      - name: Restore cache
        uses: actions/cache@v2
        with:
          key: windows-cache
          path: |
            ~/go/pkg/mod
            .tools
            .yarn/cache
            third_party
            packages/build-tools/DEPS.stamps

      - name: Delete cached build tool
        run: del .tools\tool.exe

      - name: Configure
        run: task configure msys2_path=C:\msys64 build=Release

      - name: Install dependencies
        run: task install-tools fetch-deps

      - name: Compile API definitions
        run: task proto-build

      - name: Build libarchive
        run: task libarchive-build

      - name: Build libknossos
        run: task libknossos-build

      - name: Build Knossos
        run: task client-build

      - name: Build client UI
        run: task client-ui-build

      - name: Compress final build
        run: cd build/client/launcher/Release && 7z a Knossos.7z .

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: windows-x64
          path: build/client/launcher/Release/Knossos.7z

  ubuntu-x64:
    name: Ubuntu 20.04 x64
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.8

      - name: Restore cache
        uses: actions/cache@v2
        with:
          key: ubuntu-cache
          path: |
            ~/go/pkg/mod
            .tools
            .yarn/cache
            third_party
            packages/build-tools/DEPS.stamps

      - name: Delete cached build tool
        run: rm .tools/tool

      - name: Configure
        run: ./task.sh configure build=Release

      - name: Install dependencies
        run: |
          sudo apt install -y libgtk2.0-dev liblzma-dev libzstd-dev zlib1g-dev
          ./task.sh install-tools fetch-deps

      - name: Compile API definitions
        run: ./task.sh proto-build

      - name: Build libarchive
        run: ./task.sh libarchive-build

      - name: Build libknossos
        run: ./task.sh libknossos-build

      - name: Build Knossos
        run: ./task.sh client-build

      - name: Build client UI
        run: ./task.sh client-ui-build

      - name: Compress final build
        run: cd build/client/launcher/Release && tar -cf - . | zstd > ../Knossos.tar.zstd

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-x64
          path: build/client/launcher/Knossos.tar.zstd

  darwin-x64:
    name: macOS 10.15 x64
    runs-on: macos-10.15
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.8

      - name: Restore cache
        uses: actions/cache@v2
        with:
          key: darwin-cache
          path: |
            ~/go/pkg/mod
            .tools
            .yarn/cache
            third_party
            packages/build-tools/DEPS.stamps

      - name: Delete cached build tool
        run: rm .tools/tool

      - name: Configure
        run: ./task.sh configure build=Release

      - name: Install dependencies
        run: |
          brew install xz
          ./task.sh install-tools fetch-deps

      - name: Compile API definitions
        run: ./task.sh proto-build

      - name: Build libarchive
        run: ./task.sh libarchive-build

      - name: Build libknossos
        run: ./task.sh libknossos-build

      - name: Build Knossos
        run: ./task.sh client-build

      - name: Build client UI
        run: ./task.sh client-ui-build

      - name: Compress final build
        run: cd build/client/launcher/Release && tar -cJf Knossos.tar.xz knossos.app

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: darwin-x64
          path: build/client/launcher/Release/Knossos.tar.xz
